pokemon_list = ['bulbasaur',
           'ivysaur',
           'venusaur',
           'charmander',
           'charmeleon',
           'charizard',
           'squirtle',
           'wartortle',
           'blastoise',
           'caterpie',
           'metapod',
           'butterfree',
           'weedle',
           'kakuna',
           'beedrill',
           'pidgey',
           'pidgeotto',
           'pidgeot',
           'rattata',
           'raticate',
           'spearow',
           'fearow',
           'ekans',
           'arbok',
           'pikachu',
           'raichu',
           'sandshrew',
           'sandslash',
           'nidoran_female',
           'nidorina',
           'nidoqueen',
           'nidoran_male',
           'nidorino',
           'nidoking',
           'clefairy',
           'clefable',
           'vulpix',
           'ninetales',
           'jigglypuff',
           'wigglytuff',
           'zubat',
           'golbat',
           'oddish',
           'gloom',
           'vileplume',
           'paras',
           'parasect',
           'venonat',
           'venomoth',
           'diglett',
           'dugtrio',
           'meowth',
           'persian',
           'psyduck',
           'golduck',
           'mankey',
           'primeape',
           'growlithe',
           'arcanine',
           'poliwag',
           'poliwhirl',
           'poliwrath',
           'abra',
           'kadabra',
           'alakazam',
           'machop',
           'machoke',
           'machamp',
           'bellsprout',
           'weepinbell',
           'victreebel',
           'tentacool',
           'tentacruel',
           'geodude',
           'graveler',
           'golem',
           'ponyta',
           'rapidash',
           'slowpoke',
           'slowbro',
           'magnemite',
           'magneton',
           'farfetchd',
           'doduo',
           'dodrio',
           'seel',
           'dewgong',
           'grimer',
           'muk',
           'shellder',
           'cloyster',
           'gastly',
           'haunter',
           'gengar',
           'onix',
           'drowzee',
           'hypno',
           'krabby',
           'kingler',
           'voltorb',
           'electrode',
           'exeggcute',
           'exeggutor',
           'cubone',
           'marowak',
           'hitmonlee',
           'hitmonchan',
           'lickitung',
           'koffing',
           'weezing',
           'rhyhorn',
           'rhydon',
           'chansey',
           'tangela',
           'kangaskhan',
           'horsea',
           'seadra',
           'goldeen',
           'seaking',
           'staryu',
           'starmie',
           'mr_mime',
           'scyther',
           'jynx',
           'electabuzz',
           'magmar',
           'pinsir',
           'tauros',
           'magikarp',
           'gyarados',
           'lapras',
           'ditto',
           'eevee',
           'vaporeon',
           'jolteon',
           'flareon',
           'porygon',
           'omanyte',
           'omastar',
           'kabuto',
           'kabutops',
           'aerodactyl',
           'snorlax',
           #'articuno',
           #'zapdos',
           #'moltres',
           'dratini',
           'dragonair',
           'dragonite',
           #'mewtwo',
           #'mew',
           'chikorita',
           'bayleef',
           'meganium',
           'cyndaquil',
           'quilava',
           'typhlosion',
           'totodile',
           'croconaw',
           'feraligatr',
           'sentret',
           'furret',
           'hoothoot',
           'noctowl',
           'ledyba',
           'ledian',
           'spinarak',
           'ariados',
           'crobat',
           'chinchou',
           'lanturn',
           'pichu',
           'cleffa',
           'igglybuff',
           'togepi',
           'togetic',
           'natu',
           'xatu',
           'mareep',
           'flaaffy',
           'ampharos' ,	
           'bellossom',
           'marill',
           'azumarill',
           'sudowoodo',
           'politoed',
           'hoppip',
           'skiploom',
           'jumpluff',
           'aipom',
           'sunkern',
           'sunflora',
           'yanma',
           'wooper',
           'quagsire',
           'espeon',
           'umbreon',
           'murkrow',
           'slowking',
           'misdreavus',
           'unown',
           'wobbuffet',
           'girafarig',
           'pineco',
           'forretress',
           'dunsparce',
           'gligar',
           'steelix',
           'snubbull',
           'granbull',
           'qwilfish',
           'scizor',
           'shuckle',
           'heracross',
           'sneasel',
           'teddiursa',
           'ursaring',
           'slugma',
           'magcargo',
           'swinub',
           'piloswine',
           'corsola',
           'remoraid',
           'octillery',
           'delibird',
           'mantine',
           'skarmory',
           'houndour',
           'houndoom',
           'kingdra',
           'phanpy',
           'donphan',
           'porygon2',
           'stantler',
           'smeargle',
           'tyrogue',
           'hitmontop',
           'smoochum',
           'elekid',
           'magby',
           'miltank',
           'blissey',
           #'raikou',
           #'entei',
           #'suicune',
           'larvitar',
           'pupitar',
           'tyranitar',
           #'lugia',
           #'ho-oh',
           #'celebi',
           'treecko',
           'grovyle',
           'sceptile',
           'torchic',
           'combusken',
           'blaziken',
           'mudkip',
           'marshtomp',
           'swampert',
           'poochyena',
           'mightyena',
           'zigzagoon',
           'linoone',
           'wurmple',
           'silcoon',
           'beautifly',
           'cascoon',
           'dustox',
           'lotad',
           'lombre',
           'ludicolo',
           'seedot',
           'nuzleaf',
           'shiftry',
           'taillow',
           'swellow',
           'wingull',
           'pelipper',
           'ralts',
           'kirlia',
           'gardevoir',
           'surskit',
           'masquerain',
           'shroomish',
           'breloom',
           'slakoth',
           'vigoroth',
           'slaking',
           'nincada',
           'ninjask',
           'shedinja',
           'whismur',
           'loudred',
           'exploud',
           'makuhita',
           'hariyama',
           'azurill',
           'nosepass',
           'skitty',
           'delcatty',
           'sableye',
           'mawile',
           'aron',
           'lairon',
           'aggron',
           'meditite',
           'medicham',
           'electrike',
           'manectric',
           'plusle',
           'minun',
           'volbeat',
           'illumise',
           'roselia',
           'gulpin',
           'swalot',
           'carvanha',
           'sharpedo',
           'wailmer',
           'wailord',
           'numel',
           'camerupt',
           'torkoal',
           #'spoink',
           'grumpig',
           'spinda',
           'trapinch',
           'vibrava',
           'flygon',
           'cacnea',
           'cacturne',
           'swablu',
           'altaria',
           'zangoose',
           'seviper',
           'lunatone',
           'solrock',
           'barboach',
           'whiscash',
           'corphish',
           'crawdaunt',
           'baltoy',
           'claydol',
           'lileep',
           'cradily',
           'anorith',
           'armaldo',
           'feebas',
           'milotic',
           'castform',
           'castform-rainy',
           'castform-sunny',
           'castform-snowy',
           'kecleon',
           'shuppet',
           'banette',
           'duskull',
           'dusclops',
           'tropius',
           'chimecho',
           'absol',
           'wynaut',
           'snorunt',
           'glalie',
           'spheal',
           'sealeo',
           'walrein',
           'clamperl',
           'huntail',
           'gorebyss',
           'relicanth',
           'luvdisc',
           'bagon',
           'shelgon',
           'salamence',
           'beldum',
           'metang',
           'metagross',
           #'regirock',
           #'regice',
           #'registeel',
           #'latias',
           #'latios',
           #'kyogre',
           #'groudon',
           #'rayquaza',
           #'jirachi',
           #'deoxys',
           #'deoxys_speed',
           #'deoxys_defense',
           #'deoxys_attack',
            'turtwig',
            'grotle',
            'torterra',
            'chimchar',
            'monferno',
            'infernape',
            'piplup',
            'prinplup',
            'empoleon',
            'starly',
            'staravia',
            'staraptor',
            'bidoof',
            'bibarel',
            'kricketot',
            'kricketune',
            'shinx',
            'luxio',
            'luxray',
            'budew',
            'roserade',
            'cranidos',
            'rampardos',
            'shieldon',
            'bastiodon',
            'burmy',
            'wormadam',
            'wormadam-s',
            'wormadam-t',
            'mothim',
            'combee',
            'vespiquen',
            'pachirisu',
            'buizel',
            'floatzel',
            'cherubi',
            'cherrim',
            'shellos',
            'shellos',
            'gastrodon',
            'gastrodon',
            'ambipom',
            'drifloon',
            'drifblim',
            'buneary',
            'lopunny',
            'mismagius',
            'honchkrow',
            'glameow',
            'purugly',
            'chingling',
            'stunky',
            'skuntank',
            'bronzor',
            'bronzong',
            'bonsly',
            'mime_jr',
            'happiny',
            'chatot',
            'spiritomb',
            'gible',
            'gabite',
            'garchomp',
            'munchlax',
            'riolu',
            'lucario',
            'hippopotas',
            'hippowdon',
            'skorupi',
            'drapion',
            'croagunk',
            'toxicroak',
            'carnivine',
            'finneon',
            'lumineon',
            'mantyke',
            'snover',
            'abomasnow',
            'weavile',
            'magnezone',
            'lickilicky',
            'rhyperior',
            'tangrowth',
            'electivire',
            'magmortar',
            'togekiss',
            'yanmega',
            'leafeon',
            'glaceon',
            'gliscor',
            'mamoswine',
            'porygon-z',
            'gallade',
            'probopass',
            'dusknoir',
            'froslass',
            'rotom',
            'rotom-fan',
            'rotom-frost',
            'rotom-heat',
            'rotom-mow',
            'rotom-wash'
            #'uxie',
            #'mesprit',
            #'azelf',
            #'dialga',
            #'palkia',
            #'heatran',
            #'regigigas',
            #'giratina',
            #'giratina',
            #'cresselia',
            #'phione',
            #'manaphy',
            #'darkrai',
            #'shaymin',
            #'shaymin-s',
            #'arceus',
            #'mega_'
            #:mega_abomasnow: :mega_absol: :mega_aerodactyl: :mega_aggron: :mega_alakazam: :mega_altaria: :mega_ampharos: :mega_audino: :mega_audino: :mega_banette::mega_banette: :mega_beedrill: :mega_blastoise: :mega_blaziken:  
           ]

pokemon_active = {'bulbasaur': 0,
           'ivysaur': 0,
           'venusaur': 0,
           'charmander': 0,
           'charmeleon': 0,
           'charizard': 0,
           'squirtle': 0,
           'wartortle': 0,
           'blastoise': 0,
           'caterpie': 0,
           'metapod': 0,
           'butterfree': 0,
           'weedle': 0,
           'kakuna': 0,
           'beedrill': 0,
           'pidgey': 0,
           'pidgeotto': 0,
           'pidgeot': 0,
           'rattata': 0,
           'raticate': 0,
           'spearow': 0,
           'fearow': 0,
           'ekans': 0,
           'arbok': 0,
           'pikachu': 0,
           'raichu': 0,
           'sandshrew': 0,
           'sandslash': 0,
           'nidoran_female': 0,
           'nidorina': 0,
           'nidoqueen': 0,
           'nidoran_male': 0,
           'nidorino': 0,
           'nidoking': 0,
           'clefairy': 0,
           'clefable': 0,
           'vulpix': 0,
           'ninetales': 0,
           'jigglypuff': 0,
           'wigglytuff': 0,
           'zubat': 0,
           'golbat': 0,
           'oddish': 0,
           'gloom': 0,
           'vileplume': 0,
           'paras': 0,
           'parasect': 0,
           'venonat': 0,
           'venomoth': 0,
           'diglett': 0,
           'dugtrio': 0,
           'meowth': 0,
           'persian': 0,
           'psyduck': 0,
           'golduck': 0,
           'mankey': 0,
           'primeape': 0,
           'growlithe': 0,
           'arcanine': 0,
           'poliwag': 0,
           'poliwhirl': 0,
           'poliwrath': 0,
           'abra': 0,
           'kadabra': 0,
           'alakazam': 0,
           'machop': 0,
           'machoke': 0,
           'machamp': 0,
           'bellsprout': 0,
           'weepinbell': 0,
           'victreebel': 0,
           'tentacool': 0,
           'tentacruel': 0,
           'geodude': 0,
           'graveler': 0,
           'golem': 0,
           'ponyta': 0,
           'rapidash': 0,
           'slowpoke': 0,
           'slowbro': 0,
           'magnemite': 0,
           'magneton': 0,
           'farfetchd': 0,
           'doduo': 0,
           'dodrio': 0,
           'seel': 0,
           'dewgong': 0,
           'grimer': 0,
           'muk': 0,
           'shellder': 0,
           'cloyster': 0,
           'gastly': 0,
           'haunter': 0,
           'gengar': 0,
           'onix': 0,
           'drowzee': 0,
           'hypno': 0,
           'krabby': 0,
           'kingler': 0,
           'voltorb': 0,
           'electrode': 0,
           'exeggcute': 0,
           'exeggutor': 0,
           'cubone': 0,
           'marowak': 0,
           'hitmonlee': 0,
           'hitmonchan': 0,
           'lickitung': 0,
           'koffing': 0,
           'weezing': 0,
           'rhyhorn': 0,
           'rhydon': 0,
           'chansey': 0,
           'tangela': 0,
           'kangaskhan': 0,
           'horsea': 0,
           'seadra': 0,
           'goldeen': 0,
           'seaking': 0,
           'staryu': 0,
           'starmie': 0,
           'mr_mime': 0,
           'scyther': 0,
           'jynx': 0,
           'electabuzz': 0,
           'magmar': 0,
           'pinsir': 0,
           'tauros': 0,
           'magikarp': 0,
           'gyrados': 0,
           'lapras': 0,
           'ditto': 0,
           'eevee': 0,
           'vaporeon': 0,
           'jolteon': 0,
           'flareon': 0,
           'porygon': 0,
           'omanyte': 0,
           'omastar': 0,
           'kabuto': 0,
           'kabutops': 0,
           'aerodactyl': 0,
           'snorlax': 0,
           #'articuno': 0,
           #'zapdos': 0,
           #'moltres': 0,
           'dratini': 0,
           'dragonair': 0,
           'dragonite': 0,
           #'mewtwo': 0,
           #'mew': 0
           'chikorita': 0,
           'bayleef': 0,
           'meganium': 0,
           'cyndaquil': 0,
           'quilava': 0,
           'typhlosion': 0,
           'totodile': 0,
           'croconaw': 0,
           'feraligatr': 0,
           'sentret': 0,
           'furret': 0,
           'hoothoot': 0,
           'noctowl': 0,
           'ledyba': 0,
           'ledian': 0,
           'spinarak': 0,
           'ariados': 0,
           'crobat': 0,
           'chinchou': 0,
           'lanturn': 0,
           'pichu': 0,
           'cleffa': 0,
           'igglybuff': 0,
           'togepi': 0,
           'togetic': 0,
           'natu': 0,
           'xatu': 0,
           'mareep': 0,
           'flaaffy': 0,
           'ampharos' : 0,	
           'bellossom': 0,
           'marill': 0,
           'azumarill': 0,
           'sudowoodo': 0,
           'politoed': 0,
           'hoppip': 0,
           'skiploom': 0,
           'jumpluff': 0,
           'aipom': 0,
           'sunkern': 0,
           'sunflora': 0,
           'yanma': 0,
           'wooper': 0,
           'quagsire': 0,
           'espeon': 0,
           'umbreon': 0,
           'murkrow': 0,
           'slowking': 0,
           'misdreavus': 0,
           'unown': 0,
           'wobbuffet': 0,
           'girafarig': 0,
           'pineco': 0,
           'forretress': 0,
           'dunsparce': 0,
           'gligar': 0,
           'steelix': 0,
           'snubbull': 0,
           'granbull': 0,
           'qwilfish': 0,
           'scizor': 0,
           'shuckle': 0,
           'heracross': 0,
           'sneasel': 0,
           'teddiursa': 0,
           'ursaring': 0,
           'slugma': 0,
           'magcargo': 0,
           'swinub': 0,
           'piloswine': 0,
           'corsola': 0,
           'remoraid': 0,
           'octillery': 0,
           'delibird': 0,
           'mantine': 0,
           'skarmory': 0,
           'houndour': 0,
           'houndoom': 0,
           'kingdra': 0,
           'phanpy': 0,
           'donphan': 0,
           'porygon2': 0,
           'stantler': 0,
           'smeargle': 0,
           'tyrogue': 0,
           'hitmontop': 0,
           'smoochum': 0,
           'elekid': 0,
           'magby': 0,
           'miltank': 0,
           'blissey': 0,
           #'raikou': 0,
           #'entei': 0,
           #'suicune': 0,
           'larvitar': 0,
           'pupitar': 0,
           'tyranitar': 0,
           #'lugia': 0,
           #'ho-oh': 0,
           #'celebi': 0,
           'treecko': 0,
           'grovyle': 0,
           'sceptile': 0,
           'torchic': 0,
           'combusken': 0,
           'blaziken': 0,
           'mudkip': 0,
           'marshtomp': 0,
           'swampert': 0,
           'poochyena': 0,
           'mightyena': 0,
           'zigzagoon': 0,
           'linoone': 0,
           'wurmple': 0,
           'silcoon': 0,
           'beautifly': 0,
           'cascoon': 0,
           'dustox': 0,
           'lotad': 0,
           'lombre': 0,
           'ludicolo': 0,
           'seedot': 0,
           'nuzleaf': 0,
           'shiftry': 0,
           'taillow': 0,
           'swellow': 0,
           'wingull': 0,
           'pelipper': 0,
           'ralts': 0,
           'kirlia': 0,
           'gardevoir': 0,
           'surskit': 0,
           'masquerain': 0,
           'shroomish': 0,
           'breloom': 0,
           'slakoth': 0,
           'vigoroth': 0,
           'slaking': 0,
           'nincada': 0,
           'ninjask': 0,
           'shedinja': 0,
           'whismur': 0,
           'loudred': 0,
           'exploud': 0,
           'makuhita': 0,
           'hariyama': 0,
           'azurill': 0,
           'nosepass': 0,
           'skitty': 0,
           'delcatty': 0,
           'sableye': 0,
           'mawile': 0,
           'aron': 0,
           'lairon': 0,
           'aggron': 0,
           'meditite': 0,
           'medicham': 0,
           'electrike': 0,
           'manectric': 0,
           'plusle': 0,
           'minun': 0,
           'volbeat': 0,
           'illumise': 0,
           'roselia': 0,
           'gulpin': 0,
           'swalot': 0,
           'carvanha': 0,
           'sharpedo': 0,
           'wailmer': 0,
           'wailord': 0,
           'numel': 0,
           'camerupt': 0,
           'torkoal': 0,
           #'spoink': 0,
           'grumpig': 0,
           'spinda': 0,
           'trapinch': 0,
           'vibrava': 0,
           'flygon': 0,
           'cacnea': 0,
           'cacturne': 0,
           'swablu': 0,
           'altaria': 0,
           'zangoose': 0,
           'seviper': 0,
           'lunatone': 0,
           'solrock': 0,
           'barboach': 0,
           'whiscash': 0,
           'corphish': 0,
           'crawdaunt': 0,
           'baltoy': 0,
           'claydol': 0,
           'lileep': 0,
           'cradily': 0,
           'anorith': 0,
           'armaldo': 0,
           'feebas': 0,
           'milotic': 0,
           'castform': 0,
           'castform-rainy': 0,
           'castform-sunny': 0,
           'castform -snowy': 0,
           'kecleon': 0,
           'shuppet': 0,
           'banette': 0,
           'duskull': 0,
           'dusclops': 0,
           'tropius': 0,
           'chimecho': 0,
           'absol': 0,
           'wynaut': 0,
           'snorunt': 0,
           'glalie': 0,
           'spheal': 0,
           'sealeo': 0,
           'walrein': 0,
           'clamperl': 0,
           'huntail': 0,
           'gorebyss': 0,
           'relicanth': 0,
           'luvdisc': 0,
           'bagon': 0,
           'shelgon': 0,
           'salamence': 0,
           'beldum': 0,
           'metang': 0,
           'metagross': 0,
           #'regirock': 0,
           #'regice': 0,
           #'registeel': 0,
           #'latias': 0,
           #'latios': 0,
           #'kyogre': 0,
           #'groudon': 0,
           #'rayquaza': 0,
           #'jirachi': 0,
           #'deoxys': 0,
           #'deoxys_speed': 0,
           #'deoxys_defense': 0,
           #'deoxys_attack': 0,
           'turtwig': 0,
           'grotle': 0,
           'torterra': 0,
           'chimchar': 0,
           'monferno': 0,
           'infernape': 0,
           'piplup': 0,
           'prinplup': 0,
           'empoleon': 0,
           'starly': 0,
           'staravia': 0,
           'staraptor': 0,
           'bidoof': 0,
           'bibarel': 0,
           'kricketot': 0,
           'kricketune': 0,
           'shinx': 0,
           'luxio': 0,
           'luxray': 0,
           'budew': 0,
           'roserade': 0,
           'cranidos': 0,
           'rampardos': 0,
           'shieldon': 0,
           'bastiodon': 0,
           'burmy': 0,
           'wormadam': 0,
           'wormadam-s': 0,
           'wormadam-t': 0,
           'mothim': 0,
           'combee': 0,
           'vespiquen': 0,
           'pachirisu': 0,
           'buizel': 0,
           'floatzel': 0,
           'cherubi': 0,
           'cherrim': 0,
           'shellos': 0,
           'shellos': 0,
           'gastrodon': 0,
           'gastrodon': 0,
           'ambipom': 0,
           'drifloon': 0,
           'drifblim': 0,
           'buneary': 0,
           'lopunny': 0,
           'mismagius': 0,
           'honchkrow': 0,
           'glameow': 0,
           'purugly': 0,
           'chingling': 0,
           'stunky': 0,
           'skuntank': 0,
           'bronzor': 0,
           'bronzong': 0,
           'bonsly': 0,
           'mime_jr': 0,
           'happiny': 0,
           'chatot': 0,
           'spiritomb': 0,
           'gible': 0,
           'gabite': 0,
           'garchomp': 0,
           'munchlax': 0,
           'riolu': 0,
           'lucario': 0,
           'hippopotas': 0,
           'hippowdon': 0,
           'skorupi': 0,
           'drapion': 0,
           'croagunk': 0,
           'toxicroak': 0,
           'carnivine': 0,
           'finneon': 0,
           'lumineon': 0,
           'mantyke': 0,
           'snover': 0,
           'abomasnow': 0,
           'weavile': 0,
           'magnezone': 0,
           'lickilicky': 0,
           'rhyperior': 0,
           'tangrowth': 0,
           'electivire': 0,
           'magmortar': 0,
           'togekiss': 0,
           'yanmega': 0,
           'leafeon': 0,
           'glaceon': 0,
           'gliscor': 0,
           'mamoswine': 0,
           'porygon-z': 0,
           'gallade': 0,
           'probopass': 0,
           'dusknoir': 0,
           'froslass': 0,
           'rotom': 0,
           'rotom-fan': 0,
           'rotom-frost': 0,
           'rotom-heat': 0,
           'rotom-mow': 0,
           'rotom-wash': 0
           #'uxie': 0,
           #'mesprit': 0,
           #'azelf': 0,
           #'dialga': 0,
           #'palkia': 0,
           #'heatran': 0,
           #'regigigas': 0,
           #'giratina': 0,
           #'giratina': 0,
           #'cresselia': 0,
           #'phione': 0,
           #'manaphy': 0,
           #'darkrai': 0,
           #'shaymin': 0,
           #'shaymin-s': 0,
           #'arceus': 0
           }
